on:
  pull_request:
    branches:
      - main
    types:
      - closed

name: Tag on merged PR

jobs:
  tag:
    name: Tag merged PR
    if: "github.event.pull_request.merged == true"
    runs-on: "ubuntu-latest"
    steps:
      # Setup
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64

      # Extract tag
      - name: Get Pull Request data
        id: PR
        uses: 8BitJonny/gh-get-current-pr@1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          filterOutClosed: false
      - name: Extract tag from Pull Request data
        run: "python .github/workflows/tag/extract_tag_from_pr.py"
        if: success() && steps.PR.outputs.number
        env:
          PR_JSON_DATA: "${{ steps.PR.outputs.pr }}"
      - name: Read tag from output file
        id: tagRead
        uses: juliangruber/read-file-action@v1
        if: success() && steps.PR.outputs.number
        with:
          path: "./version.txt"

      # Push tag
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        if: success() && steps.PR.outputs.number && steps.tagRead.outputs.content
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.tagRead.outputs.content }}"

      # Trigger release sending tag (Github Workflows cannot be triggered by other workflows actions by default)
      - name: Trigger Release workflow
        uses: peter-evans/repository-dispatch@v1
        if: success() && steps.PR.outputs.number && steps.tagRead.outputs.content
        with:
          token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          repository: "David-Lor/GTAV-SimpleGangWar"
          event-type: "from_tag"
          client-payload: '{"tag": "${{ steps.tagRead.outputs.content }}"}'
